name: DevSecOps Pipeline (Trivy Scan)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  security-scan:
    name: Scansione Vulnerabilità
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Scarica il codice dal repository
      - name: Checkout del codice
        uses: actions/checkout@v4

      # Step 2: Lancia Trivy (Scanner di Sicurezza Open Source)
      - name: Analisi Vulnerabilità e Segreti
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs' # Scansiona il file system (codice sorgente e Dockerfile)
          format: 'table' # Mostra i risultati in una bella tabella nei log
          exit-code: '1'  # Se trova problemi critici, fa fallire (rompe) la pipeline
          severity: 'CRITICAL,HIGH' # Cerca solo vulnerabilità Alte o Critiche
